# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14793b3b1a1bb9603a1639b93406a3e28d2a5334f49d78ed4efa3510327ca1b38fcb4ea57c3ccb77370647814b36e87314924674fde212e9969be10c0751096e

test:
  secret_key_base: 80a58b29362741fda9b778dda3d83171454830f9d2acc2ad36e8a9675b1f154f56f28d204ede67e6dd64b39aac8f4e22a6af57e9a003306b4fd09f173a5706cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
